#!/bin/bash -e

updateAmiClient() {
    message "Updating AMI Client code and bash scripts."
    updateAmiClientCode
    updateAmiClientBashScripts
}

updateAmiClientCode() {
    local buildDir="${AMI_CLIENT_DIR}/build"
    local nodeModulesDir="${AMI_CLIENT_DIR}/node_modules"
    local nodeModulesInstallDir="${AMI_CLIENT_INSTALL_DIR}/node_modules"
    (cd "${AMI_CLIENT_DIR}" && npm run build)
    mkdir -p "${AMI_CLIENT_INSTALL_DIR}"
    deleteAndSyncDirectory "${buildDir}" "${AMI_CLIENT_INSTALL_DIR}" >/dev/null
    mkdir -p "${nodeModulesInstallDir}"
    deleteAndSyncDirectory "${nodeModulesDir}" "${nodeModulesInstallDir}" >/dev/null
}

updateAmiClientBashScripts() {
    deleteAndSyncDirectory "${AMI_CLIENT_SCRIPTS_DIR}" "${AMI_CLIENT_SCRIPTS_INSTALL_DIR}" >/dev/null
}
