#!/bin/bash -e

updateAsteriskConfig() {
    message 'Updating Asterisk config files.'

    local templateConfigDir="$(doTemplateReplacement "${ASTERISK_CONFIG_DIR}" asterisk asterisk)"
    chmod 755 "${templateConfigDir}"
    deleteAndSyncDirectory "${templateConfigDir}" "${ASTERISK_CONFIG_INSTALL_DIR}"
}
