#!/bin/bash -e

updateDatadir() {
    updateDataSoundsFiles
}

updateDataSoundsFiles() {
    message 'Updating Asterisk data sound files...'
    installWavSoundFiles "${DATA_SOUNDS_DIR}" "${DATA_SOUNDS_INSTALL_DIR}" "${SOUNDS_FORMATS}"
    chmod 750 "${DATA_SOUNDS_INSTALL_DIR}"
    chown -R asterisk:asterisk "${DATA_SOUNDS_INSTALL_DIR}"
}
