#!/bin/bash -e

updateVoicemail() {
    message 'Updating voicemail.'
    updateVoicemailSoundFiles
}

updateVoicemailSoundFiles() {
    # Delete greeting and unavailable messages in all formats.
    find "$(voicemailSoundsInstallDir)" -maxdepth 1 -type f '(' -name 'unavail.*' ')' -delete

    # Put custom unavailable message instead (which has length 0.00s).
    installWavSoundFiles "${VOICEMAIL_SOUNDS_DIR}" "$(voicemailSoundsInstallDir)" "${SOUNDS_FORMATS}"
    chmod -R 750 "$(voicemailSoundsInstallDir)"
    chown asterisk:asterisk "$(voicemailSoundsInstallDir)"
}
